export default function Limitation() {
  return (
    <div className="relative px-4 sm:px-6 lg:px-8 font-worksans-light">
      <div className="text-lg max-w-prose mx-auto">
        <h4>
          <span className="block text-base mt-8 text-blue-600 tracking-wide uppercase font-worksans-light">
            11. Limitaciones de responsabilidad
          </span>
        </h4>
        <p className="mt-4 text-xl text-gray-500 leading-8">
          EN LA MEDIDA EN QUE LO PERMITA LA LEY, EN NINGÚN CASO SoloPython (O NUESTROS PROVEEDORES)
          SERÁN RESPONSABLES ANTE USTED O CUALQUIER TERCERO POR CUALQUIER PÉRDIDA DE BENEFICIOS,
          PÉRDIDA DE DATOS, COSTOS DE OBTENCIÓN DE PRODUCTOS SUSTITUTIVOS, O CUALQUIER DAÑO
          INDIRECTO, CONSECUENTES, EJEMPLARES, INCIDENTALES, ESPECIALES O PUNITIVOS QUE SE DERIVEN
          DE O ESTÉN RELACIONADOS CON ESTAS CONDICIONES O CON EL USO QUE USTED HAGA DEL SERVICIO O
          LA IMPOSIBILIDAD DE USARLO, INCLUSO SI SoloPython HA SIDO ADVERTIDO DE LA POSIBILIDAD DE
          DICHOS DAÑOS. EL ACCESO Y EL USO DEL SERVICIO ES A SU PROPIA DISCRECIÓN Y RIESGO, Y USTED
          SERÁ EL ÚNICO RESPONSABLE DE CUALQUIER DAÑO A SU DISPOSITIVO O SISTEMA INFORMÁTICO, O DE
          LA PÉRDIDA DE DATOS QUE RESULTE DE ELLO.
        </p>
      </div>

      <div className="text-lg max-w-prose mx-auto">
        <p className="mt-4 text-xl text-gray-500 leading-8">
          EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEY, Y SIN PERJUICIO DE CUALQUIER DISPOSICIÓN
          CONTRARIA CONTENIDA EN EL PRESENTE DOCUMENTO, NUESTRA RESPONSABILIDAD ANTE USTED POR
          CUALQUIER DAÑO DERIVADO DE ESTE ACUERDO O RELACIONADO CON ÉL (POR CUALQUIER CAUSA E
          INDEPENDIENTEMENTE DE LA FORMA DE LA ACCIÓN), SE LIMITARÁ EN TODO MOMENTO A UN MÁXIMO DE
          LAS CANTIDADES PAGADAS A NOSOTROS POR USTED EN LOS DOCE (12) MESES ANTERIORES AL EVENTO
          QUE DIO LUGAR A LA RECLAMACIÓN. LA EXISTENCIA DE MÁS DE UNA RECLAMACIÓN NO AMPLIARÁ ESTE
          LÍMITE. USTED ACEPTA QUE NUESTROS PROVEEDORES NO TENDRÁN NINGUNA RESPONSABILIDAD DE NINGÚN
          TIPO DERIVADA DE ESTE ACUERDO O RELACIONADA CON ÉL
        </p>
      </div>
      <div className="text-lg max-w-prose mx-auto">
        <p className="mt-4 text-xl text-gray-500 leading-8">
          ALGUNAS JURISDICCIONES NO PERMITEN LA LIMITACIÓN O EXCLUSIÓN DE RESPONSABILIDAD POR DAÑOS
          INCIDENTALES O CONSECUENTES, POR LO QUE ES POSIBLE QUE LA LIMITACIÓN O EXCLUSIÓN ANTERIOR
          NO SE APLIQUE EN SU CASO.
        </p>
      </div>
    </div>
  );
}
